In [158]:
import numpy as np
import random

In [159]:
class Geometry:
    count = 0
    def __init__(self, name = "Shape", points = None):
        self.name = name
        # name is string that is a name of gemoetry
        self.points = points
        # points is a list of tuple points = [(x0, y0), (x1, y1), ...]
        Geometry.count += 1

    def calculate_area(self):
        pass

    def get_name(self):
        return self.name

    @classmethod
    def count_number_of_geometry(cls):
        # TODO: Your task is to implement the class method
        # to get the number of instance that have already created
        return Geometry.count


In [160]:
class Triangle(Geometry):
    def __init__(self, a, b, c):
        # a, b, c are tuples that represent for 3 vertices of a triangle
        # TODO: Your task is to implement the constructor
        super(Triangle, self).__init__("Triangle", [a,b,c])


    def calculate_area(self):
        #TODO: Your task is required to implement a area function
        x1, y1 = self.points[0]
        x2, y2 = self.points[1]
        x3, y3 = self.points[2]
        return abs((x1*(y2 - y3) + x2*(y3 - y1) + x3*(y1 - y2)) / 2.0)

In [161]:
class Rectangle(Geometry):
    def __init__(self, a, b):
        # a, b are tuples that represent for top and bottom vertices of a rectangle
        # TODO: Your task is to implement the constructor
        super(Rectangle, self).__init__("Rectangle", [a, b])

    def calculate_area(self):
        #TODO: Your task is required to implement a area function
        x1, y1 = self.points[0]
        x2, y2 = self.points[1]
        return abs((x2 - x1) * (y2 - y1))


In [162]:
class Square(Rectangle):
    def __init__(self, a, length):
        # a is a tuple that represent a top vertex of a square
        # length is the side length of a square
        # TODO: Your task is to implement the constructor
        b = (a[0] + length, a[1] - length)
        super(Square, self).__init__(a, b)
        self.length = length
        self.name = "Square"

    def calculate_area(self):
        #TODO: Your task is required to implement a area function
        return self.length ** 2

In [163]:
class Circle(Geometry):
    def __init__(self, o, r):
        # o is a tuple that represent a centre of a circle
        # r is the radius of a circle
        # TODO: Your task is to implement the constructor
        super(Circle, self).__init__("Circle", [o])
        self.r = r

    def calculate_area(self):
        #TODO: Your task is required to implement a area function
        return np.pi * (self.r ** 2)

In [164]:
class Polygon(Geometry):
    def __init__(self, points):
        # points is a list of tuples that represent vertices of a polygon
        # TODO: Your task is to implement the constructor
        super(Polygon, self).__init__("Polygon", points)

    def calculate_area(self):
        #TODO: Your task is required to implement a area function
        n = len(self.points)
        area = 0
        for i in range(n):
          x1, y1 = self.points[i]
          x2, y2 = self.points[(i + 1) % n]
          area += (x1 * y2 - x2 * y1)
        return abs(area) / 2

In [165]:
def test_geomery():
    ## Test cases for Problem 1

    triangle = Triangle((0, 1), (1, 0), (0, 0))
    print("Area of %s: %0.4f" % (triangle.name, triangle.calculate_area()))

    rectangle = Rectangle((0, 0), (2, 2))
    print("Area of %s: %0.4f" % (rectangle.name, rectangle.calculate_area()))

    square = Square((0, 0), 2)
    print("Area of %s: %0.4f" % (square.name, square.calculate_area()))

    circle = Circle((0, 0), 3)
    print("Area of %s: %0.4f" % (circle.name, circle.calculate_area()))

    polygon = Polygon([(0, 0), (0, 1), (1, 1), (1, 0)])
    print("Area of %s: %0.4f" % (polygon.name, polygon.calculate_area()))

In [166]:
test_geomery()

Area of Triangle: 0.5000
Area of Rectangle: 4.0000
Area of Square: 4.0000
Area of Circle: 28.2743
Area of Polygon: 1.0000


In [167]:
def matrix_multiplication(A, B):
    # TODO: Your task is to required to implement
    # a matrix multiplication between A and B
    m, k = A.shape
    _, n = B.shape
    C = np.zeros((m, n))
    for i in range(m):
      for j in range(n):
        for t in range(k):
          C[i][j] += A[i, t] * B[t, j]
    return C
A = np.random.randn(4, 5)
B = np.random.randn(5, 6)
assert np.mean(np.abs(A.dot(B) - matrix_multiplication(A, B))) <= 1e-7, "Your implmentation is wrong!"

print("Your implementation is correct!")

Your implementation is correct!


In [168]:
def test_matrix_mul():
    ## Test cases for matrix multplication ##

    for test in range(10):
        m, n, k = random.randint(3, 10), random.randint(3, 10), random.randint(3, 10)
        A = np.random.randn(m, n)
        B = np.random.randn(n, k)
        assert np.mean(np.abs(A.dot(B) - matrix_multiplication(A, B))) <= 1e-7, "Your implmentation is wrong!"
        print("[Test Case %d]. Your implementation is correct!" % test)

In [169]:
test_matrix_mul()

[Test Case 0]. Your implementation is correct!
[Test Case 1]. Your implementation is correct!
[Test Case 2]. Your implementation is correct!
[Test Case 3]. Your implementation is correct!
[Test Case 4]. Your implementation is correct!
[Test Case 5]. Your implementation is correct!
[Test Case 6]. Your implementation is correct!
[Test Case 7]. Your implementation is correct!
[Test Case 8]. Your implementation is correct!
[Test Case 9]. Your implementation is correct!


In [170]:
def recursive_pow(A, n):
    # TODO: Your task is required implementing
    # a recursive function
    if n == 0:
      return np.eye(A.shape[0])
    else:
      B = recursive_pow(A, n // 2)
      B = B @ B
      if n % 2 == 0:
        return B
      else:
        return B @ A

In [171]:
def iterative_pow(A, n):
	  # TODO: Your task is required implementing
    # a iterative function
    result = np.eye(A.shape[0])
    while n > 0:
      if n % 2 == 1:
        result = result @ A
      A = A @ A
      n = n // 2
    return result

In [172]:
def test_pow():
    ## Test cases for the pow function ##

    for test in range(10):
        n = random.randint(2, 5)
        A = np.random.randn(n, n)
        print("Recursive: A^{} = {}".format(n, recursive_pow(A, n)))

    for test in range(10):
        n = random.randint(2, 5)
        A = np.random.randn(n, n)
        print("Iterative: A^{} = {}".format(n, iterative_pow(A, n)))

In [173]:
test_pow()

Recursive: A^3 = [[-1.17729826  1.56280582  2.62707024]
 [ 8.27898689 -8.01635022 -1.55958823]
 [ 0.35603233  0.28781726  3.51788507]]
Recursive: A^3 = [[ 1.37504802 -1.35401839  2.8672233 ]
 [-7.34075271  5.54406431 -7.77636587]
 [ 5.40311869 -4.14446685  5.97321963]]
Recursive: A^5 = [[  4.35881097   4.49533999  -2.22606652  -6.88203682  -4.01251593]
 [ -6.84012372  43.41743045  -5.14045791 -27.12610589  -1.34282768]
 [  2.96918979  19.44214891  -3.82020814 -13.75055803  -1.78737707]
 [  5.57685091  -8.41406794   0.08160689   2.8973547   -1.11876453]
 [ -1.48991607   9.65246706  -1.04864201  -2.33872971   2.59316961]]
Recursive: A^4 = [[-0.83451844 -2.17928416  1.61478835 10.66739896]
 [-0.21842687  6.26804197  2.47097369  9.42408297]
 [ 4.07616528  3.43708141  4.91338575  2.69414538]
 [-3.45203113 -7.91596689 -4.15552713 -1.58693615]]
Recursive: A^2 = [[ 4.75719668 -2.72251146]
 [ 1.06050737 -0.40721928]]
Recursive: A^3 = [[-1.53029063 -0.48015789 -3.33582203]
 [-0.25919244 -0.39065

In [174]:
def get_A():
    # TODO: Find a matrix A
    # You have to return in the format of numpy array
    return np.array([[1, 1], [1, 0]])

def fibo(n):
    # TODO: Calcualte the n'th Fibonacci number
    if n == 0:
        return 1
    A = get_A()
    result = recursive_pow(A, n - 1)
    return result[0, 0] + result[0, 1]

In [175]:
def f(n, k):
    # TODO: Calcualte the n'th number of the recursive sequence
    if n < k:
        return 1
    A = np.zeros((k, k))
    for i in range(k - 1):
        A[i, i + 1] = 1
    A[k - 1] = np.ones(k)
    An = recursive_pow(A, n - k + 1)
    F = np.ones((k, 1))
    return int(np.matmul(An, F)[-1, 0])

In [176]:
def test_fibonacci():
    ## Test Cases for Fibonacci and Recursive Sequence ##
    a, b = 1, 1
    for i in range(2, 10):
        c = a + b
        assert (fibo(i) == c), "You implementation is incorrect"
        print("[Test Case %d]. Your implementation is correct!. fibo(%d) = %d" % (i - 2, i, fibo(i)))
        a = b
        b = c

    for n in range(5, 11):
        for k in range(2, 5):
            print("f(%d, %d) = %d" % (n, k, f(n, k)))

In [177]:
test_fibonacci()

[Test Case 0]. Your implementation is correct!. fibo(2) = 2
[Test Case 1]. Your implementation is correct!. fibo(3) = 3
[Test Case 2]. Your implementation is correct!. fibo(4) = 5
[Test Case 3]. Your implementation is correct!. fibo(5) = 8
[Test Case 4]. Your implementation is correct!. fibo(6) = 13
[Test Case 5]. Your implementation is correct!. fibo(7) = 21
[Test Case 6]. Your implementation is correct!. fibo(8) = 34
[Test Case 7]. Your implementation is correct!. fibo(9) = 55
f(5, 2) = 8
f(5, 3) = 9
f(5, 4) = 7
f(6, 2) = 13
f(6, 3) = 17
f(6, 4) = 13
f(7, 2) = 21
f(7, 3) = 31
f(7, 4) = 25
f(8, 2) = 34
f(8, 3) = 57
f(8, 4) = 49
f(9, 2) = 55
f(9, 3) = 105
f(9, 4) = 94
f(10, 2) = 89
f(10, 3) = 193
f(10, 4) = 181


In [ ]:
from collections import deque
import heapq

In [ ]:
def DFS(A):
    # A is a mxn matrix
    if not A.any() or A[0][0] == 0 or A[-1][-1] == 0:
        print(-1)
        return
    m, n = A.shape
    directions = [(0,1), (1,0), (0,-1), (-1,0)]
    path = []
    visited = set()
    def dfs(x, y):
        if (x, y) == (m-1, n-1):
            path.append((x, y))
            return True
        visited.add((x, y))
        path.append((x, y))
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < m and 0 <= ny < n and A[nx][ny] == 1 and (nx, ny) not in visited:
                if dfs(nx, ny):
                    return True
        path.pop()
        return False
    if dfs(0, 0):
        print(" → ".join(map(str, path)))
    else:
        print(-1)

In [ ]:
def BFS(A):
    # A is a mxn matrix
    if not A.any() or A[0][0] == 0 or A[-1][-1] == 0:
        print(-1)
        return
    m, n = A.shape
    directions = [(0,1), (1,0), (0,-1), (-1,0)]
    queue = deque([(0, 0, [(0, 0)])])
    visited = set([(0, 0)])
    while queue:
        x, y, path = queue.popleft()
        if (x, y) == (m-1, n-1):
            print(" → ".join(map(str, path)))
            return
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < m and 0 <= ny < n and A[nx][ny] == 1 and (nx, ny) not in visited:
                visited.add((nx, ny))
                queue.append((nx, ny, path + [(nx, ny)]))
    print(-1)

In [179]:
def findMinimum(A):
    # A is a mxn matrix
    if not A.any() or A[0][0] == 0 or A[-1][-1] == 0:
        print(-1)
        return
    m, n = A.shape
    directions = [(0,1), (1,0), (0,-1), (-1,0)]
    min_heap = [(A[0][0], 0, 0, [(0, 0)])]  # (cost, x, y, path)
    visited = set()
    while min_heap:
        cost, x, y, path = heapq.heappop(min_heap)
        if (x, y) == (m-1, n-1):
            print(" → ".join(map(str, path)))
            print("Total value:", cost)
            return
        if (x, y) in visited:
            continue
        visited.add((x, y))
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < m and 0 <= ny < n and A[nx][ny] > 0 and (nx, ny) not in visited:
                heapq.heappush(min_heap, (cost + A[nx][ny], nx, ny, path + [(nx, ny)]))
    print(-1)

In [180]:
def test_bfs_dfs_find_minimum():
    ## Test Cases for BFS, DFS, Find Minimum ##
    A = np.array([[1, 1, 1, 0, 1],
                  [0, 0, 1, 0, 0],
                  [1, 1, 1, 1, 1],
                  [1, 1, 0, 1, 1],
                  [1, 1, 0, 1, 1]])

    print("BFS Output:")
    BFS(A)

    print("\nDFS Output:")
    DFS(A)

    A = np.array([[1, 1, 1, 0, 1],
                  [0, 0, 1, 0, 0],
                  [1, 1, 1, 1, 2],
                  [1, 1, 0, 2, 1],
                  [1, 1, 0, 2, 1]])

    print("\nFind Minimum Output:")
    findMinimum(A)

test_bfs_dfs_find_minimum()

BFS Output:
(0, 0) → (0, 1) → (0, 2) → (1, 2) → (2, 2) → (2, 3) → (2, 4) → (3, 4) → (4, 4)

DFS Output:
(0, 0) → (0, 1) → (0, 2) → (1, 2) → (2, 2) → (2, 3) → (2, 4) → (3, 4) → (4, 4)

Find Minimum Output:
(0, 0) → (0, 1) → (0, 2) → (1, 2) → (2, 2) → (2, 3) → (2, 4) → (3, 4) → (4, 4)
Total value: 10
